hibernate.driver_class = org.postgresql.Driver
hibernate.connection.url = jdbc:postgresql://localhost:5432/shoes
hibernate.connection.username = postgres
hibernate.connection.password = Lol228666

hibernate.dialect = org.hibernate.dialect.PostgresPlusDialect
hibernate.show_sql = true
hibernate.current_session_context_class = thread